Vagrant.configure("2") do |config|
    config.vm.define "lab1" do |subconfig|
        subconfig.vm.box = "ubuntu/focal64"
        subconfig.vm.hostname="lab1"
        subconfig.vm.network "private_network", 
            ip: "192.168.0.2",
            netmask: "255.255.255.0",
            virtualbox__intnet: true,
            virtualbox__intnet:"intneta"
        subconfig.vm.network "private_network",
            ip: "192.168.2.2",
            virtualbox__intnet: true,
            virtualbox__intnet:"intnetb"
        subconfig.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "4096"]
            vb.customize ["modifyvm", :id, "--cpus", "2"]
            # enable promiscuous mode on the network
            vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
            vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
        end
        subconfig.vm.provision "file", source: "server.conf", destination: "~/server.conf"
        subconfig.vm.provision "file", source: "server_route.conf", destination: "~/server_route.conf"
        subconfig.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
        #config.vm.synced_folder "sync_folder", "/sync_folder"
        subconfig.vm.provision "shell", inline: <<-SHELL
            cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
            echo 1 > /proc/sys/net/ipv4/ip_forward
            sudo echo "192.168.0.3 lab2" | sudo tee -a /etc/hosts
            sudo echo "192.168.2.3 lab3" | sudo tee -a /etc/hosts
            sudo apt update
            sudo apt install -y net-tools inetutils-traceroute nmap openvpn bridge-utils
        SHELL
        subconfig.vm.provision "shell", path: "lab1.sh"
    end

    config.vm.define "lab2" do |subconfig|
        subconfig.vm.box = "ubuntu/focal64"
        subconfig.vm.hostname="lab2"
        subconfig.vm.network "private_network", 
            ip: "192.168.0.3",
            netmask: "255.255.255.0",
            virtualbox__intnet: true,
            virtualbox__intnet:"intneta"
        subconfig.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "4096"]
            vb.customize ["modifyvm", :id, "--cpus", "2"]
            # enable promiscuous mode on the network
            vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        end
        subconfig.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
        subconfig.vm.provision "shell", inline: <<-SHELL
            cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
            sudo echo "192.168.0.2 lab1" | sudo tee -a /etc/hosts
            sudo echo "192.168.2.3 lab3" | sudo tee -a /etc/hosts
            sudo apt update
            sudo apt install -y net-tools inetutils-traceroute nmap openvpn bridge-utils
        SHELL
       # subconfig.vm.provision "shell", path: "lab2.sh"
    end


    config.vm.define "lab3" do |subconfig|
        subconfig.vm.box = "ubuntu/focal64"
        subconfig.vm.hostname="lab3"
        subconfig.vm.network "private_network", 
            ip: "192.168.2.3",
            netmask: "255.255.255.0",
            virtualbox__intnet: true,
            virtualbox__intnet:"intnetb"
        subconfig.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "4096"]
            vb.customize ["modifyvm", :id, "--cpus", "2"]
            # enable promiscuous mode on the network
            vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        end
        subconfig.vm.provision "file", source: "client.conf", destination: "~/client.conf"
        subconfig.vm.provision "file", source: "client_route.conf", destination: "~/client_route.conf"
        subconfig.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
        subconfig.vm.provision "shell", inline: <<-SHELL
            cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
            sudo echo "192.168.2.2 lab1" | sudo tee -a /etc/hosts
            sudo echo "192.168.0.3 lab2" | sudo tee -a /etc/hosts
            sudo apt update
            sudo apt install -y net-tools inetutils-traceroute nmap openvpn bridge-utils
        SHELL
        subconfig.vm.provision "shell", path: "lab3.sh"
    end
end